### ISSUE TITLE
Config magento root dir

### ISSUE THREAD

**Issue by vmasciotta** [AydinHassan/magento-core-composer-installer#39]
Hi,
first of all I'd like to thank you for your great module.

I wanted to ask if is safe to use 
```
...
"magento-root-dir": "./"
"magento-deploystrategy": "copy"
...
```
instead to deploy into a subdir like `src` or `public_html` etc. 

I'm asking for this because sometimes happen that hosting providers doesn't provide the option to change the root dir on the main domain and messing around into the magento index.php to redirect for a single store website is not the best.

Thanks

**Comment by AydinHassan** [comment]
hi @vmasciotta yes it is safe to change the root dir, it is all detailed in the readme. You cannot change the deploy strategy, it is copy only. Symlink is not supported as magento core doesn't work with symlinks due to some direct file references, but anyway, that shouldn't be a problem if as you stated you wanted to use copy.

I'll close this now, but feel free to ask any more questions here 😄
